### PR TITLE
Fix build for external ROS

### PR DESCRIPTION
**Pull request by hamlittle**

### CODE REVIEW

**Comment by hamlittle** [comment]
@Lou-Graniou can you test the build and make sure it works on your end?

**Review by MarcBrau — APPROVED** [review]
LGTM and works like a charm! Thank you for putting it together that fast!

**Comment by MarcBrau** [comment]
@hamlittle: Can you please also update [this line](https://github.com/ZendarInc/zendar_ros_driver/blob/d5fc2c6c4431332c21ec76a41ebe180bed1b57af/include/zendar_ros_driver/tracks.h#L6)? I added it without being aware of the changes in your PR.

**Comment by hamlittle** [comment]
> @hamlittle: Can you please also update [this line](https://github.com/ZendarInc/zendar_ros_driver/blob/d5fc2c6c4431332c21ec76a41ebe180bed1b57af/include/zendar_ros_driver/tracks.h#L6)? I added it without being aware of the changes in your PR. It should be: `#include <zendar/client/api/api.h>`

@MarcBrau done.

**Pull request merged**
